# Generated by Django 5.1.4 on 2024-12-07 16:19

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='شماره موبایل به عنوان یوزرنیم', max_length=15, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('verified', models.BooleanField(default=False, help_text='آیا شماره موبایل کاربر تأیید شده است؟')),
                ('otp_verified', models.BooleanField(default=False, help_text='آیا کد OTP تأیید شده است؟')),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_expiry_date', models.DateField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_card_image', models.ImageField(blank=True, null=True, upload_to='bank_card_images/')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('national_id', fernet_fields.fields.EncryptedCharField(help_text='شماره ملی رمزگذاری\u200cشده', max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_document_image', models.ImageField(blank=True, null=True, upload_to='id_documents/')),
                ('score', models.IntegerField(default=0, help_text='امتیاز کاربر')),
                ('theme', models.CharField(choices=[('light', 'روشن'), ('dark', 'تاریک')], default='light', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group', verbose_name='گروه\u200cها')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission', verbose_name='مجوزها')),
            ],
            options={
                'permissions': [('can_view_dashboard', 'Can view the dashboard'), ('can_manage_users', 'Can manage user accounts'), ('can_manage_transactions', 'Can manage transactions'), ('can_view_reports', 'Can view reports'), ('can_manage_dashboard', 'Can access dashboard'), ('can_manage_profile', 'Can manage personal profile'), ('can_manage_company', 'Can manage company information'), ('can_manage_contacts', 'Can manage contacts'), ('can_manage_addresses', 'Can manage addresses')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('mobile', 'Mobile'), ('home', 'Home'), ('work', 'Work')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customer_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=10)),
                ('economic_code', models.CharField(max_length=50)),
                ('office_address', models.TextField()),
                ('warehouse_address', models.TextField(blank=True, null=True)),
                ('ceo_name', models.CharField(max_length=100)),
                ('ceo_phone', models.CharField(max_length=15)),
                ('ceo_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ceo_documents', models.FileField(upload_to='ceo_documents/')),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_person_position', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person_phone', models.CharField(max_length=15)),
                ('company_documents', models.FileField(upload_to='company_documents/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='customer_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('warehouse', 'Warehouse')], max_length=20)),
                ('address_line', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customer_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='customer_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='عملیات انجام\u200cشده', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('settlement_method', models.CharField(choices=[('bank_card', 'Bank Card'), ('iban', 'IBAN'), ('cash', 'Cash')], max_length=20)),
                ('settlement_cycle', models.CharField(blank=True, choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=20, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('outstanding_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_transactions', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customer_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserSensitiveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', fernet_fields.fields.EncryptedCharField(help_text='شماره کارت بانکی رمزگذاری\u200cشده', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer_app.customuser')),
            ],
        ),
    ]
